version: 0.2
phases:
        install:
                runtime-version:
                        python: 3.8
        pre_build:
                commands:
                        - pip install -r requirements.txt
                        - python app_test.py
